# spring.datasource.url=jdbc:h2:mem:cars
# spring.jpa.show-sql=true
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:mysql://localhost:3306/carsdb
spring.datasource.username=carsManager
spring.datasource.password=FJKTuPLhmYUcW8q73VUJ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.data.rest.base-path=/api